# -*- coding: utf-8 -*-
"""Basic ML.1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ed4fTy8MjFPuLsRk-XJCQ7YZSU5VZo4S
"""

import pandas as pd
data = {
    'Name': ['Tayyab', 'Irfan', 'Jwad', 'Kamail'],
    'age': [21, None, 44, 23],
    'salary': [50000, None, None, 60000]
}

df=pd.DataFrame(data)
print("Original Dataframe")
print(df)
print(df.isnull(). mean()*100)

print(df.isnull().sum())

df_drop=df.dropna()
print(df_drop)

df['age'].fillna(df['age'].mean(),inplace=True)
df['salary'].fillna(df['salary'].mean(),inplace=True)
print(df)

import pandas as pd
df=pd.read_csv("dataset_with_missing.csv")
print(df)
print(df.isnull().mean()*100)

print(df.isnull().sum())

df_drop=df.dropna()
print(df_drop)

df['Age'].fillna(df['Age'].mean(),inplace=True)
df['Salary'].fillna(df['Salary'].mean(),inplace=True)
df['Department'].fillna(df['Department'].mode()[1],inplace=True)
print(df)

