# -*- coding: utf-8 -*-
"""KNN Algorithm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tmDtohxKJqcFzP0BNQLZfHAnJhmLML2c
"""

from sklearn.neighbors import KNeighborsClassifier
X=[
    [180,7],
    [200,7.5],
    [250,8],
    [300,8.5],
    [330,9],
    [360,9.5],
]
y=[0,0,0,1,1,1]
model=KNeighborsClassifier(n_neighbors=3)
model.fit(X,y)
weight=float(input("Enter the weight of in grams"))
size=float(input("Enter the size in cm"))
result=model.predict([ [weight,size]])[[0]]
if result==0:
  print("This is likely an Apple 🍎")
else:
     print("This is likely an Orange 🍊")