# -*- coding: utf-8 -*-
"""Linear regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dvZE8S7fIuvsmoUY51LnZuhMOekZ8Dc7
"""

from sklearn.linear_model import LinearRegression
X=[[1],[2],[3],[4],[5]]
y=[50,60,70,90,100]
model=LinearRegression()
model.fit(X,y)
hours=float(input("Enter your studying hours="))
predicted_model=model.predict([[hours]])
print(f"based on your  study hours {hours} you may score around{predicted_model}")