# -*- coding: utf-8 -*-
"""Logistic regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uBPP33vnp8ePwJo8Cienevrk-90WtUVZ
"""

from sklearn.linear_model import LogisticRegression
X=[[1],[2],[3],[4],[5],[6]]
y=[0,0,0,1,1,1]
model=LogisticRegression()
model.fit(X,y)
hours=float(input("Enter your study hous"))
result=model.predict([[hours]])[0]
if result==1:
  print(f"ont the behalf of your study hours {hours} you are likely to PASS ✅")
else:
    print(f"ont the behalf of your study hours {hours} you are likely to FAIL ❌")