# -*- coding: utf-8 -*-
"""ML.2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jQlPTB5DKdSKbnAaEz4vzMUO74xhWamH
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.model_selection import train_test_split
data={
    'study hours':[1,2,3,4,5],
    'score marks':[40,50,70,90,85]
}
df=pd.DataFrame(data)
standard_scaler = StandardScaler()
standard_scale= standard_scaler.fit_transform(df)
print("standad_scaler Output")
print(pd.DataFrame(standard_scale,columns=['study hours','score marks']))

minmax_scaler=MinMaxScaler()
Minmax_scaler=minmax_scaler.fit_transform(df)
print("/nmimmax scaler output")
print(pd.DataFrame(Minmax_scaler,columns=['study hours','score marks']))
# for training and testing
X=df[['study hours']]
y=df[['score marks']]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
print("training data")
print(X_train)
print("/n testing data")
print(X_test)

print("training data")
print(y_train)
print("/n testing data")
print(y_test)